POST http://localhost:8080/article/
Accept: application/json
Content-Type: application/json

{
  "title": "test de Symfony",
  "content": "bla bla",
  "author": {
    "name": "",
    "firstName": "Fabien",
    "login": "fab",
    "password": "123"
  }

}